const Homescreen_Api = 'https://reapp.com.gh/wp-json/wp/v2/home-api';
const Login_Api ='https://reapp.com.gh/wp-json/jwt-auth/v1/token';
const Forgotpassword = 'https://reapp.com.gh/wp-content/themes/classiads-child/template-forget-password-api.php';
const CategoriesId_Api ='https://reapp.com.gh/wp-json/wp/v2/sub-category?categ_id=';
const getUsertProfile_Api = "https://reapp.com.gh/api/fetch_user.php?id=" ;
const Location_Api = "https://reapp.com.gh/wp-json/wp/v2/location?user_id=";
const Singleproduct_api = "https://reapp.com.gh/wp-json/wp/v2/posts/";
const Fetchpost_Api = "https://reapp.com.gh/api/fetch_post.php?id=";
const ProductTag_Api = "https://reapp.com.gh/wp-json/wp/v2/posts?user_id=";
const getCategory_Api = "https://reapp.com.gh/wp-json/wp/v2/sub-category?categ_id=";
const getProductList = "https://reapp.com.gh/wp-json/wp/v2/search-posts?user_id=";
const getWishlist_APi = "https://reapp.com.gh/wp-json/wp/v2/get-wishlist?user_id=";
const DeleteWishlist_Api = "https://reapp.com.gh/wp-json/wp/v2/delete-wishlist";
const SaveWishlist = "https://reapp.com.gh/wp-json/wp/v2/add-wishlist";
const DeleteMyAds_Api = "https://reapp.com.gh/api/delete_post.php";
const Createnewad_Api = "https://reapp.com.gh/wp-content/themes/classiads-child/template-new-ad-api.php";
const Stock_Api = "https://reapp.com.gh/api/stock_list.php";
const Brand_Api = "https://reapp.com.gh/api/brand_list.php";
const Changepassword_APi = "https://reapp.com.gh/wp-json/wp/v2/change-password";
